name: Kubernetes
on: 
  push:
    branches:
      - main
jobs:
  install-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Install k3s
        run: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy traefik" sh -s -
          kubectl get nodes
