name: Kubernetes
on: 
  workflow_dispatch:
jobs:
  install-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - name: Verify k3s installtion
        run: |
          kubectl get nodes
      - name: Deploy the app
        run: |
          pwd
          ls -lrth
          cd kube/
          kubectl apply -f deploy.yml
